trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  input:
    versionSpec:'18.x'
  displayName: 'Install Node.js'

- script: 
    npm install
    npm run build
  displayName: "Build App'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'drop'
  displayName: 'Publish Build Artifact'
